"""usuario

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 22:10:01.005221

Cria a conta de usuário com perfil, desativação e o estado do bloqueio por conta em colunas
(RN-34, RN-37, RN-60). Login único no estabelecimento sem diferenciar maiúsculas: índice
único sobre `lower(login)`.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuario",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("estabelecimento_id", sa.BigInteger(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("login", sa.Text(), nullable=False),
        sa.Column("senha_hash", sa.Text(), nullable=False),
        sa.Column(
            "perfil",
            # O CHECK do perfil é o ck_usuario_perfil abaixo; o Enum não cria outro.
            sa.Enum("ADMIN", "OPERADOR", name="perfil", native_enum=False, create_constraint=False),
            nullable=False,
        ),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("falhas_consecutivas", sa.Integer(), nullable=False),
        sa.Column("bloqueios", sa.Integer(), nullable=False),
        sa.Column("bloqueado_ate", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("perfil IN ('ADMIN', 'OPERADOR')", name=op.f("ck_usuario_perfil")),
        sa.ForeignKeyConstraint(
            ["estabelecimento_id"],
            ["estabelecimento.id"],
            name=op.f("fk_usuario_estabelecimento_id_estabelecimento"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuario")),
    )
    op.create_index(
        "uq_usuario_estabelecimento_id_login",
        "usuario",
        ["estabelecimento_id", sa.literal_column("lower(login)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_usuario_estabelecimento_id_login", table_name="usuario")
    op.drop_table("usuario")
    # ### end Alembic commands ###
