"""venda

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-08 21:53:06.776641
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "venda",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("estabelecimento_id", sa.BigInteger(), nullable=False),
        sa.Column("item_cardapio_id", sa.BigInteger(), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("prato_nome", sa.Text(), nullable=False),
        sa.Column("proteina_nome", sa.Text(), nullable=False),
        sa.Column(
            "formato",
            sa.Enum("PF", "MARMITA", name="formato", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("preco_unitario", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("gramas_por_porcao", sa.Integer(), nullable=False),
        sa.Column("valor_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("proteina_total_g", sa.Integer(), nullable=False),
        sa.Column("registrada_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("registrada_por", sa.BigInteger(), nullable=False),
        sa.Column("chave_idempotencia", sa.Text(), nullable=False),
        sa.Column("cancelada_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelada_por", sa.BigInteger(), nullable=True),
        sa.Column("motivo_cancelamento", sa.Text(), nullable=True),
        sa.CheckConstraint("formato IN ('PF', 'MARMITA')", name=op.f("ck_venda_formato_valido")),
        sa.CheckConstraint(
            "quantidade BETWEEN 1 AND 20", name=op.f("ck_venda_quantidade_no_limite")
        ),
        sa.ForeignKeyConstraint(
            ["cancelada_por"], ["usuario.id"], name=op.f("fk_venda_cancelada_por_usuario")
        ),
        sa.ForeignKeyConstraint(
            ["estabelecimento_id"],
            ["estabelecimento.id"],
            name=op.f("fk_venda_estabelecimento_id_estabelecimento"),
        ),
        sa.ForeignKeyConstraint(
            ["item_cardapio_id"],
            ["item_cardapio.id"],
            name=op.f("fk_venda_item_cardapio_id_item_cardapio"),
        ),
        sa.ForeignKeyConstraint(
            ["registrada_por"], ["usuario.id"], name=op.f("fk_venda_registrada_por_usuario")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venda")),
    )
    op.create_index(
        "ix_venda_estabelecimento_id_registrada_em",
        "venda",
        ["estabelecimento_id", "registrada_em"],
        unique=False,
    )
    op.create_index(
        "uq_venda_estabelecimento_id_chave_idempotencia",
        "venda",
        ["estabelecimento_id", "chave_idempotencia"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_venda_estabelecimento_id_chave_idempotencia", table_name="venda")
    op.drop_index("ix_venda_estabelecimento_id_registrada_em", table_name="venda")
    op.drop_table("venda")
    # ### end Alembic commands ###
